@RecipeAPI_HostAddress = http://localhost:5000

GET {{RecipeAPI_HostAddress}}/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVG9tbXkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzgyMDc4MjcxLCJpc3MiOiJSZWNpcGVBUEkiLCJhdWQiOiJSZWNpcGVBUElVc2VycyJ9.K_VlkfL7XRJyyh8iGiGMsuBCkpCS0kCoeK9TFBhrjJg

###